name: Lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: $(( ${{ github.event.pull_request.commits }} + 1 ))
      - name: Fetch main with enough history for a common merge-base commit
        run: git fetch origin ${{ github.event.pull_request.base.ref }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run linters
        run: LINT_CHECK=true npx lint-staged --diff="origin/${{ github.event.pull_request.base.ref }}...${{ github.event.pull_request.head.ref }}" --verbose
